# Numpy Basics <hr style="border:2.5px solid #82127cff"></hr>

<b>Lance Marco F. Baltazar</b>
<br>TUPV Computer Engineering CpE-2A

In [46]:
#%pip install numpy --upgrade
#%pip install scipy --upgrade

In [ ]:
#%pip install --upgrade pip

In [48]:
# imports and packages
import numpy as np
from scipy import stats
from statistics import multimode

# 1D Array

In [49]:
# 1-dimensional array
array_a = np.array([1,2,3])
array_a

array([1, 2, 3])

In [50]:
# size of an array
np.shape(array_a)

(3,)

In [51]:
# 1-dimensional array
array_b = np.array([4,5,6])
array_b

array([4, 5, 6])

In [52]:
my_array = [1,2,3]

In [53]:
my_array

[1, 2, 3]

In [54]:
array_name = np.array

my_array = np.array([1,2,3])

In [55]:
np.shape(my_array)

(3,)

# 2D Array

In [56]:
# 2-dimensional array
my_array = np.array([
    [1,2,3],
    [4,5,6]
])
my_array

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
# size of matrix
np.shape(my_array)

(2, 3)

In [58]:
# transpose of a matrix
t_array = my_array.T
t_array

array([[1, 4],
       [2, 5],
       [3, 6]])

In [59]:
# size of matrix
np.shape(t_array)

(3, 2)

In [60]:
trans_array = my_array.T

In [61]:
np.shape(my_array)

(2, 3)

In [62]:
trans_array

array([[1, 4],
       [2, 5],
       [3, 6]])

In [63]:
np.shape(trans_array)

(3, 2)

In [64]:
np.sum(trans_array,axis=0)

array([ 6, 15])

In [65]:
np.sum(trans_array,axis=1)

array([5, 7, 9])

# Measure of Central Tendency

In [66]:
# Jaguar vs Panther
resistance = np.array([
    [10.6,9.1,9.3,9.8,10.5,10.4,9.5,11,10.4,3,9.8], #Jaguar
    [10.1,11,9.1,20,9.2,10.8,9.9,9.2,9.1,9.1,np.nan] #Panther
])
resistance

array([[10.6,  9.1,  9.3,  9.8, 10.5, 10.4,  9.5, 11. , 10.4,  3. ,  9.8],
       [10.1, 11. ,  9.1, 20. ,  9.2, 10.8,  9.9,  9.2,  9.1,  9.1,  nan]])

In [67]:
np.shape(resistance)

(2, 11)

In [68]:
resistance.T

array([[10.6, 10.1],
       [ 9.1, 11. ],
       [ 9.3,  9.1],
       [ 9.8, 20. ],
       [10.5,  9.2],
       [10.4, 10.8],
       [ 9.5,  9.9],
       [11. ,  9.2],
       [10.4,  9.1],
       [ 3. ,  9.1],
       [ 9.8,  nan]])

In [69]:
np.mean(resistance,axis=0)

array([10.35, 10.05,  9.2 , 14.9 ,  9.85, 10.6 ,  9.7 , 10.1 ,  9.75,
        6.05,   nan])

In [70]:
np.mean(resistance,axis=1)

array([9.4, nan])

In [71]:
# Mean
np.nanmean(resistance,axis=1)

array([ 9.4 , 10.75])

In [72]:
jag_mean = np.nanmean(resistance,axis=1)[0]
pan_mean = np.nanmean(resistance,axis=1)[1]

print(f'Jaguar_mean = {jag_mean:.2f} ohms')
print(f'Panther_mean = {pan_mean:.2f} ohms')

Jaguar_mean = 9.40 ohms
Panther_mean = 10.75 ohms


In [73]:
# Median
np.nanmedian(resistance,axis=1)

array([9.8 , 9.55])

In [74]:
jag_median = np.nanmedian(resistance,axis=1)[0]
pan_median = np.nanmedian(resistance,axis=1)[1]

print(f'Jaguar_median = {jag_median:.2f} ohms')
print(f'Panther_median = {pan_median:.2f} ohms')

Jaguar_median = 9.80 ohms
Panther_median = 9.55 ohms


In [75]:
# Mode
stats.mode(resistance,axis=1)

ModeResult(mode=array([9.8, 9.1]), count=array([2, 3]))

In [76]:
my_array = [1,1,2,2,3,4,5]
multimode(my_array)

[1, 2]

In [77]:
jag_res = resistance[0]

print("Jaguar mode:")
for i in multimode(jag_res):
    print(f'{i} ohms')

Jaguar mode:
9.8 ohms
10.4 ohms


In [78]:
pan_res = resistance[1]

print("Panther mode:")
for i in multimode(pan_res):
    print(f'{i} ohms')

Panther mode:
9.1 ohms


# Measures of Variability

In [79]:
# Jaguar vs Panther
resistance = np.array([
    [10.6,9.1,9.3,9.8,10.5,10.4,9.5,11,10.4,3,9.8], #Jaguar
    [10.1,11,9.1,20,9.2,10.8,9.9,9.2,9.1,9.1,np.nan] #Panther
])
resistance

array([[10.6,  9.1,  9.3,  9.8, 10.5, 10.4,  9.5, 11. , 10.4,  3. ,  9.8],
       [10.1, 11. ,  9.1, 20. ,  9.2, 10.8,  9.9,  9.2,  9.1,  9.1,  nan]])

In [80]:
# Range
res_max = np.nanmax(resistance,axis=1)
res_min = np.nanmin(resistance,axis=1)

res_range = res_max - res_min
res_range

array([ 8. , 10.9])

In [81]:
print(f'Jaguar_range = {res_range[0]:.2f} ohms')
print(f'Panther_range = {res_range[1]:.2f} ohms')

Jaguar_range = 8.00 ohms
Panther_range = 10.90 ohms


In [82]:
# 1st Quartile
res_Q1 = np.nanpercentile(resistance,25,axis=1)
res_Q1

array([9.4  , 9.125])

In [83]:
# 2nd Quartile
res_Q2 = np.nanpercentile(resistance,50,axis=1)
res_Q2

array([9.8 , 9.55])

In [84]:
# 3rd Quartile
res_Q3 = np.nanpercentile(resistance,75,axis=1)
res_Q3

array([10.45 , 10.625])

In [85]:
# IQR
print(f'Jaguar IQR = {res_Q3[0] - res_Q1[0]:.2f} ohms')
print(f'Panther IQR = {res_Q3[1] - res_Q1[1]:.2f} ohms')

Jaguar IQR = 1.05 ohms
Panther IQR = 1.50 ohms


In [86]:
# Variance
res_var = np.nanvar(resistance,ddof=1,axis=1)
res_var

array([ 4.86      , 11.08277778])

In [87]:
print(f'Jaguar Variance = {res_var[0]:.2f} ohms')
print(f'Panther Variance = {res_var[1]:.2f} ohms')

Jaguar Variance = 4.86 ohms
Panther Variance = 11.08 ohms


In [88]:
# Standard Deviation
res_std = np.nanstd(resistance,ddof=1,axis=1)
res_std

array([2.20454077, 3.32908062])

In [89]:
print(f'Jaguar Standard Deviation = {res_std[0]:.2f} ohms')
print(f'Panther Standard Deviation = {res_std[1]:.2f} ohms')

Jaguar Standard Deviation = 2.20 ohms
Panther Standard Deviation = 3.33 ohms
